### app config
pipeline:
  enabled: 'true'

app:
  name: simpletour-sale-admin
  build_label: maven
  build_cmd: mvn clean package -B -U -Dmaven.test.skip=true
  template: war
  namespace: "udev"
  url_uat: saleadmin.uat.simpletour.com
  url_prod: saleadmin.simpletour.com
  url_path: "/"
  runEnv: {}
    # env: uat
  runArgs: []
  # - "-Dspring.profiles.active=local"

### helm charts config
replicaCount: 1
image:
  repository: hub.simpletour.com/udev/simpletour-sale-admin
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-devops
service:
  name: simpletour-sale-admin
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  protocol: TCP
ingress:
  enabled: true
  path: /
  hosts:
    - chart-example.local
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
  labels:
    realm: internal  # internal|external
probe: {}