### app config
pipeline:
  enabled: 'true'

app:
  name: simpletour-dist-web
  build_label: maven
  build_cmd: mvn clean package -B -U -Dmaven.test.skip=true -pl simpletour-dist-web -am
  template: war
  namespace: "bdev"
  url_uat: uat.newdistweb.simpletour.com
  url_prod: newdistweb.simpletour.com
  url_path: "/"
  runEnv: {}
    # env: uat
  runArgs: []
  # - "-Dspring.profiles.active=local"

### helm charts config
replicaCount: 1
image:
  repository: hub.simpletour.com/bdev/simpletour-dist-web
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-devops
service:
  name: simpletour-dist-web
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  protocol: TCP
ingress:
  enabled: true
  path: /
  hosts:
    - chart-example.local
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
  labels:
    realm: internal  # internal|external
probe: {}